# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Clean the build"
  lane :clean do
    gradle(task: "clean")
  end
  desc "After successful execution of task, Push code to Github"
  after_all do
      git_add(path: "*")
      git_commit(path: "*", message: "Setting up Worker with DaggerHilt,WorkRequest")
      push_to_git_remote(local_branch: "main",
              remote: "origin",
              remote_branch: "main", tags: true)
  end
end
